.test-cirrus:
  # Tests that require full virtualization are delegated to Cirrus CI
  stage: test
  image: potyarkin/cirrus-run
  script:
    - test -n "${CIRRUS_API_TOKEN}" && cirrus-run
  variables:
    CIRRUS_GITHUB_REPO: bonzini/.cirrus-ci-jobs
    # CIRRUS_API_TOKEN: Masked value. Defined in GitLab web interface


